export const TRAER_TAREAS = 'tareas_traer_todas'
export const CARGANDO = 'tareas_cargando'
export const ERROR = 'tareas_error'
export const CAMBIO_USUARIO_ID = 'cambio_usuario_id'
export const CAMBIO_TITULO = 'cambio_titulo'
export const AGREGADA = 'tareas_agregadas'